/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_MARS_BLUETOOTH_HCI__
#define __RUST_MARS_BLUETOOTH_HCI__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  A representation of a serialized data buffer.
 *
 *  This is used for handing off memory from rust to a C application, and vice-versa.
 *  If this was allocated from a rust vector, it has to be freed by rust.
 */
typedef struct SerializedData {
    /** \brief
     *  A pointer to the buffer that holds serialized data.
     */
    uint8_t * p_data;

    /** \brief
     *  The size of the buffer.
     */
    size_t size;

    /** \brief
     *  The maximum capacity of the buffer in byte.
     */
    size_t capacity;
} SerializedData_t;

/** \brief
 *  Drop previously allocated memory.
 */
void
drop_bin (
    SerializedData_t serialized);


#include <stdbool.h>

/** \brief
 *  Allocate `length` bytes in heap memory, and fill them with increasing u8 values.
 *
 *  If `use_cobs` is `true`, allocates at least two times `length` bytes and performs COBS encoding.
 *
 *  # Safety
 *  Dereferences the raw pointer for `written_length`. Make sure it is valid.
 */
uint8_t const *
new_dummy_data (
    size_t length,
    bool use_cobs,
    size_t * written_length);

/** \brief
 *  Serialize a log message to [`SerializedData`].
 *
 *  # Safety
 *  Dereferences the raw pointer for `p_log_message`. Make sure it is valid.
 */
SerializedData_t
serialize_log_message (
    int8_t const * p_log_message,
    bool use_cobs);

/** \brief
 *  The origin of data.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum Origin {
    /** \brief
     *  Origin is unknown.
     */
    ORIGIN_UNKNOWN,
    /** \brief
     *  Data from an initiator. Carries MAC address identifier.
     */
    ORIGIN_INITIATOR,
    /** \brief
     *  Data from a reflector. Carries MAC address identifier.
     */
    ORIGIN_REFLECTOR,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
Origin_t;

/** \brief
 *  Done status (shared by procedures and subevents).
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum DoneStatus {
    /** \brief
     *  All procedures/subevents are complete.
     */
    DONE_STATUS_ALL_COMPLETE = 0,
    /** \brief
     *  Procedures/subevents are partially complete. More are going to follow.
     */
    DONE_STATUS_PARTIAL = 1,
    /** \brief
     *  The procedure/subevent was aborted.
     */
    DONE_STATUS_ABORTED = 15,
    /** \brief
     *  Reserved status (catch-all for unknown values).
     */
    DONE_STATUS_RESERVED = 255,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
DoneStatus_t;

/** \brief
 *  Reasons for aborting procedures.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ProcedureAbortReason {
    /** \brief
     *  The procedure was not aborted.
     */
    PROCEDURE_ABORT_REASON_NO_ABORT,
    /** \brief
     *  Abort caused by local host or a remote request.
     */
    PROCEDURE_ABORT_REASON_LOCAL_HOST_OR_REMOTE_REQUEST,
    /** \brief
     *  Less than 15 channels where used for measurement.
     */
    PROCEDURE_ABORT_REASON_LESS_THAN15_CHANNELS,
    /** \brief
     *  The channel map update instant has passed.
     */
    PROCEDURE_ABORT_REASON_CHANNEL_MAP_UPDATE_INSTANT_PASSED,
    /** \brief
     *  Unspecified abort reason.
     */
    PROCEDURE_ABORT_REASON_UNSPECIFIED,
    /** \brief
     *  Reserved abort reason.
     */
    PROCEDURE_ABORT_REASON_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ProcedureAbortReason_t;

/** \brief
 *  Reasons for aborting subevents.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum SubeventAbortReason {
    /** \brief
     *  The subevent was not aborted.
     */
    SUBEVENT_ABORT_REASON_NO_ABORT,
    /** \brief
     *  Abort caused by local host or a remote request.
     */
    SUBEVENT_ABORT_REASON_LOCAL_HOST_OR_REMOTE_REQUEST,
    /** \brief
     *  No CS sync was received.
     */
    SUBEVENT_ABORT_REASON_NO_CS_SYNC_RECEIVED,
    /** \brief
     *  Scheduling conflict or limited resources.
     */
    SUBEVENT_ABORT_REASON_SCHEDULING_CONFLICT_OR_LIMITED_RESOURCES,
    /** \brief
     *  Unspecified abort reason.
     */
    SUBEVENT_ABORT_REASON_UNSPECIFIED,
    /** \brief
     *  Reserved abort reason.
     */
    SUBEVENT_ABORT_REASON_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
SubeventAbortReason_t;

/** \brief
 *  Discriminant for [`ModeRoleSpecificInfo`].
 *
 *  # Step-mode support limitation
 *
 *  Only [`ModeRoleSpecificInfoKind::Mode2`] is populated by the parser: [`Mode2`]
 *  step data is decoded in [`SubeventResultEvent`]'s parse path. Mode 0 is
 *  recognized but carries no step data (a no-op), and Mode 1 / Mode 3 step inputs
 *  return [`ParseError::InvalidModeType`]. The Mode 1 and Mode 3 variants here
 *  exist for ABI completeness so the C enum stays forward-compatible. Implementing
 *  the remaining modes is tracked in
 *  <https://github.com/Metironic/mars-bluetooth-hci/issues/9>.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ModeRoleSpecificInfoKind {
    /** \brief
     *  Mode 0, reflector role. Recognized by the parser but carries no step data.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE0_REFLECTOR,
    /** \brief
     *  Mode 1, initiator role. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_INITIATOR,
    /** \brief
     *  Mode 1, initiator role, with PBR and RTT measurements. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_INITIATOR_PBR_RTT,
    /** \brief
     *  Mode 1, reflector role. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_REFLECTOR,
    /** \brief
     *  Mode 1, reflector role, with PBR and RTT measurements. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_REFLECTOR_PBR_RTT,
    /** \brief
     *  Mode 2. The only step mode populated by the parser (see [`Mode2`]).
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE2,
    /** \brief
     *  Mode 3, initiator role. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_INITIATOR,
    /** \brief
     *  Mode 3, initiator role, with PBR and RTT measurements. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_INITIATOR_PBR_RTT,
    /** \brief
     *  Mode 3, reflector role. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_REFLECTOR,
    /** \brief
     *  Mode 3, reflector role, with PBR and RTT measurements. Not populated by the parser.
     */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_REFLECTOR_PBR_RTT,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ModeRoleSpecificInfoKind_t;

/** \brief
 *  Decoded contents of the packet quality byte.
 */
typedef struct PacketQuality {
    /** \brief
     *  Result of the access address check from the low nibble.
     */
    uint8_t access_address_check_result;

    /** \brief
     *  Payload bit error count from the high nibble.
     */
    uint8_t payload_bit_error_count;
} PacketQuality_t;

/** \brief
 *  Packet-level fields shared by time-based ranging modes.
 */
typedef struct RoundTripTimePacketFields {
    /** \brief
     *  Decoded packet quality fields.
     */
    PacketQuality_t packet_quality;

    /** \brief
     *  Normalized attack detector metric for the packet.
     */
    uint8_t packet_normalized_attack_detector_metric;

    /** \brief
     *  Received signal strength indicator for the packet.
     */
    int8_t packet_received_signal_strength_indicator;

    /** \brief
     *  Antenna used for the packet measurement.
     */
    uint8_t packet_antenna;
} RoundTripTimePacketFields_t;

/** \brief
 *  Indicates which role-specific timing interpretation is valid.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum RoundTripTimeRoleTimingKind {
    /** \brief
     *  No role-specific timing has been assigned yet.
     */
    ROUND_TRIP_TIME_ROLE_TIMING_KIND_UNAVAILABLE,
    /** \brief
     *  Timing field `ToA_ToD_Initiator`.
     */
    ROUND_TRIP_TIME_ROLE_TIMING_KIND_TIME_OF_ARRIVAL_TIME_OF_DEPARTURE_INITIATOR,
    /** \brief
     *  Timing field `ToD_ToA_Reflector`.
     */
    ROUND_TRIP_TIME_ROLE_TIMING_KIND_TIME_OF_DEPARTURE_TIME_OF_ARRIVAL_REFLECTOR,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
RoundTripTimeRoleTimingKind_t;

/** \brief
 *  Role-specific time delta for time-based ranging.
 *
 *  The raw role-specific timing value uses a time base of `0.5 ns` per least significant bit.
 */
typedef struct RoundTripTimeRoleTiming {
    /** \brief
     *  Indicates which role-specific timing field is valid.
     */
    RoundTripTimeRoleTimingKind_t kind;

    /** \brief
     *  Signed value of the selected role-specific timing field.
     *
     *  Stored with a time base of `0.5 ns` per least significant bit.
     */
    int16_t role_specific_timing_value;
} RoundTripTimeRoleTiming_t;

/** \brief
 *  The phase correction term (PCT), composed of I and Q components.
 */
typedef struct PhaseCorrectionTerm {
    /** \brief
     *  The I component of the PCT.
     */
    float i;

    /** \brief
     *  The Q component of the PCT.
     */
    float q;
} PhaseCorrectionTerm_t;

/** \brief
 *  Optional packet phase correction terms for enhanced packet-based ranging.
 */
typedef struct PacketPhaseCorrectionTerms {
    /** \brief
     *  First packet phase correction term.
     */
    PhaseCorrectionTerm_t first_phase_correction_term;

    /** \brief
     *  Second packet phase correction term.
     */
    PhaseCorrectionTerm_t second_phase_correction_term;
} PacketPhaseCorrectionTerms_t;

/** \brief
 *  Compact Mode 1 payload stored once per reported step.
 */
typedef struct Mode1Data {
    /** \brief
     *  Shared packet-level fields.
     */
    RoundTripTimePacketFields_t packet;

    /** \brief
     *  Role-specific RTT timing delta.
     */
    RoundTripTimeRoleTiming_t timing;

    /** \brief
     *  Optional packet phase correction terms.
     */
    PacketPhaseCorrectionTerms_t packet_phase_correction_terms;

    /** \brief
     *  If true, `packet_phase_correction_terms` is valid.
     */
    bool has_packet_phase_correction_terms;
} Mode1Data_t;

typedef struct {
    PhaseCorrectionTerm_t idx[5];
} PhaseCorrectionTerm_5_array_t;

/** \brief
 *  An indicator of tone quality
 *
 *  Order of entries is important, as it is used for sorting.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ToneQualityIndicator {
    /** \brief
     *  Reserved tone quality indicator.
     */
    TONE_QUALITY_INDICATOR_RESERVED,
    /** \brief
     *  Tone quality is unavailable.
     */
    TONE_QUALITY_INDICATOR_UNAVAILABLE,
    /** \brief
     *  Tone quality is low.
     */
    TONE_QUALITY_INDICATOR_LOW,
    /** \brief
     *  Tone quality is medium.
     */
    TONE_QUALITY_INDICATOR_MEDIUM,
    /** \brief
     *  Tone quality is high.
     */
    TONE_QUALITY_INDICATOR_HIGH,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ToneQualityIndicator_t;

typedef struct {
    ToneQualityIndicator_t idx[5];
} ToneQualityIndicator_5_array_t;

/** \brief
 *  Possible types of extension slots.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ExtensionSlot {
    /** \brief
     *  No extension slot is present.
     */
    EXTENSION_SLOT_NOT_PRESENT,
    /** \brief
     *  An extension slot is present but not expected.
     */
    EXTENSION_SLOT_NOT_EXPECTED_PRESENT,
    /** \brief
     *  An extension slot is present and expected.
     */
    EXTENSION_SLOT_EXPECTED_PRESENT,
    /** \brief
     *  Reserved slot type.
     */
    EXTENSION_SLOT_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ExtensionSlot_t;

typedef struct {
    ExtensionSlot_t idx[5];
} ExtensionSlot_5_array_t;

/** \brief
 *  Content of a Mode2 that is captured in a step.
 */
typedef struct Mode2 {
    /** \brief
     *  The selected antenna permutation index.
     */
    uint8_t antenna_permutation_index;

    /** \brief
     *  The phase correction terms for the antenna paths.
     */
    PhaseCorrectionTerm_5_array_t phase_correction_terms;

    /** \brief
     *  The quality indicators for the antenna paths.
     */
    ToneQualityIndicator_5_array_t quality_indicators;

    /** \brief
     *  The selected extension slots for the antenna paths.
     */
    ExtensionSlot_5_array_t extension_slots;
} Mode2_t;

/** \brief
 *  Mode- and role-specific information.
 *
 *  The payload fields are selected by `kind`.
 */
typedef struct ModeRoleSpecificInfo {
    /** \brief
     *  The kind of mode- and role-specific information.
     */
    ModeRoleSpecificInfoKind_t kind;

    /** \brief
     *  Mode1 data. Valid when `kind`
     *  is [`ModeRoleSpecificInfoKind::Mode1Initiator`]
     *  or [`ModeRoleSpecificInfoKind::Mode1InitiatorPbrRtt`]
     *  or [`ModeRoleSpecificInfoKind::Mode1Reflector`]
     *  or [`ModeRoleSpecificInfoKind::Mode1ReflectorPbrRtt`],
     *  and also for Mode 3 variants (Mode 3 = Mode 1 + Mode 2 in the spec).
     */
    Mode1Data_t mode1;

    /** \brief
     *  Mode2 data. Valid when `kind`
     *  is [`ModeRoleSpecificInfoKind::Mode2`],
     *  and also for Mode 3 variants (the tone fields are populated alongside
     *  Mode 1 packet fields in `mode1`).
     */
    Mode2_t mode2;
} ModeRoleSpecificInfo_t;

/** \brief
 *  Data that characterizes a step.
 */
typedef struct Step {
    /** \brief
     *  The type of mode.
     */
    uint8_t mode;

    /** \brief
     *  The selected frequency channel.
     */
    uint8_t channel;

    /** \brief
     *  Information that is specific to the mode and role of a node.
     */
    ModeRoleSpecificInfo_t info;
} Step_t;

typedef struct {
    Step_t idx[160];
} Step_160_array_t;

/** \brief
 *  The relative frequency error compensation.
 */
typedef struct FrequencyCompensation {
    /** \brief
     *  The compensation value in steps of 0.01 ppm.
     */
    uint16_t value;
} FrequencyCompensation_t;

/** \brief
 *  A reference power level in dBm.
 */
typedef struct ReferencePowerLevel {
    /** \brief
     *  The reference power level value in dBm, from -127 to 20.
     */
    int8_t value;
} ReferencePowerLevel_t;

/** \brief
 *  Metadata that is contained only in the initial HCI_LE_CS_Config_Complete subevent.
 */
typedef struct InitialMeta {
    /** \brief
     *  Starting ACL connection event counter for the results reported in the event.
     */
    uint16_t start_acl_conn_event_counter;

    /** \brief
     *  If true, the metadata contains a valid starting ACL connection event counter.
     */
    bool has_start_acl_conn_event_counter;

    /** \brief
     *  CS procedure count since completion of the Channel Sounding Security Start procedure.
     */
    uint16_t procedure_counter;

    /** \brief
     *  Frequency compensation with a resolution of 0.01 ppm.
     */
    FrequencyCompensation_t frequency_compensation;

    /** \brief
     *  The reference power level between -127 and 20 dBm.
     */
    ReferencePowerLevel_t reference_power_level;
} InitialMeta_t;

/** \brief
 *  Data that was collected from a "LE CS Subevent Result event" [7.7.65.44, p. 2446]
 *  or a "LE CS Subevent Result Continue event" [7.7.65.45, p. 2459].
 *
 *  For the latter, the [`SubeventResultEvent::initial_meta`] is `None`.
 *
 *  See the `TryFrom<&[u8]>` implementation for a parse-from-bytes example.
 */
typedef struct SubeventResultEvent {
    /** \brief
     *  The origin of the data (initiator or reflector).
     *
     *  Left at [`Origin::Unknown`] by the parser; the caller sets this from
     *  out-of-band context (which node produced the bytes), as the file-reader
     *  helper does.
     */
    Origin_t origin;

    /** \brief
     *  MAC address of the local node.
     *
     *  Left at `0` by the parser; the caller sets this from out-of-band context.
     */
    uint64_t local_mac;

    /** \brief
     *  MAC address of the peer node.
     *
     *  Left at `0` by the parser; the caller sets this from out-of-band context.
     */
    uint64_t peer_mac;

    /** \brief
     *  The connection handle between two nodes.
     */
    uint16_t connection_handle;

    /** \brief
     *  CS configuration identifier.
     */
    uint8_t config_id;

    /** \brief
     *  If true, has valid config ID.
     */
    bool has_config_id;

    /** \brief
     *  State of the procedure.
     */
    DoneStatus_t procedure_done_status;

    /** \brief
     *  The procedure abort reason, if any.
     */
    ProcedureAbortReason_t procedure_abort_reason;

    /** \brief
     *  State of the subevent.
     */
    DoneStatus_t subevent_done_status;

    /** \brief
     *  The subevent abort reason, if any.
     */
    SubeventAbortReason_t subevent_abort_reason;

    /** \brief
     *  The number of antenna paths.
     */
    size_t antenna_path_count;

    /** \brief
     *  The number of steps for the subevent.
     */
    size_t step_count;

    /** \brief
     *  The step data.
     */
    Step_160_array_t steps;

    /** \brief
     *  Metadata that only the first subevent (not the "continue" variant) holds.
     */
    InitialMeta_t initial_meta;

    /** \brief
     *  If true, initial metadata is available.
     */
    bool has_initial_meta;
} SubeventResultEvent_t;

/** \brief
 *  Serialize a subevent result event to [`SerializedData`].
 */
SerializedData_t
serialize_subevent_result_event (
    SubeventResultEvent_t const * p_event,
    bool use_cobs);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_MARS_BLUETOOTH_HCI__ */
