/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_BLUETOOTH_HCI__
#define __RUST_BLUETOOTH_HCI__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  A representation of a serialized data buffer.
 *
 *  This is used for handing off memory from rust to a C application, and vice-versa.
 *  If this was allocated from a rust vector, it has to be freed by rust.
 */
typedef struct SerializedData {
    /** \brief
     *  A pointer to the buffer that holds serialized data.
     */
    uint8_t * p_data;

    /** \brief
     *  The size of the buffer.
     */
    size_t size;

    /** \brief
     *  The maximum capacity of the buffer in byte.
     */
    size_t capacity;
} SerializedData_t;

/** \brief
 *  Drop previously allocated memory.
 */
void
drop_bin (
    SerializedData_t serialized);


#include <stdbool.h>

/** \brief
 *  Allocate `length` bytes in heap memory, and fill them with increasing u8 values.
 *
 *  If `use_cobs` is `true`, allocates at least two times `length` bytes and performs COBS encoding.
 *
 *  # Safety
 *  Dereferences the raw pointer for `written_length`. Make sure it is valid.
 */
uint8_t const *
new_dummy_data (
    size_t length,
    bool use_cobs,
    size_t * written_length);

/** \brief
 *  Serialize a log message to [`SerializedData`].
 *
 *  # Safety
 *  Dereferences the raw pointer for `p_log_message`. Make sure it is valid.
 */
SerializedData_t
serialize_log_message (
    int8_t const * p_log_message,
    bool use_cobs);

/** \brief
 *  The origin of data.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum Origin {
    /** \brief
     *  Origin is unknown.
     */
    ORIGIN_UNKNOWN,
    /** \brief
     *  Data from an initiator. Carries MAC address identifier.
     */
    ORIGIN_INITIATOR,
    /** \brief
     *  Data from a reflector. Carries MAC address identifier.
     */
    ORIGIN_REFLECTOR,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
Origin_t;

/** \brief
 *  Done status (shared by procedures and subevents).
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum DoneStatus {
    /** \brief
     *  All procedures/subevents are complete.
     */
    DONE_STATUS_ALL_COMPLETE = 0,
    /** \brief
     *  Procedures/subevents are partially complete. More are going to follow.
     */
    DONE_STATUS_PARTIAL = 1,
    /** \brief
     *  The procedure/subevent was aborted.
     */
    DONE_STATUS_ABORTED = 15,
    /** \brief
     *  Reserved status (catch-all for unknown values).
     */
    DONE_STATUS_RESERVED = 255,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
DoneStatus_t;

/** \brief
 *  Reasons for aborting procedures.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ProcedureAbortReason {
    /** \brief
     *  The procedure was not aborted.
     */
    PROCEDURE_ABORT_REASON_NO_ABORT,
    /** \brief
     *  Abort caused by local host or a remote request.
     */
    PROCEDURE_ABORT_REASON_LOCAL_HOST_OR_REMOTE_REQUEST,
    /** \brief
     *  Less than 15 channels where used for measurement.
     */
    PROCEDURE_ABORT_REASON_LESS_THAN15_CHANNELS,
    /** \brief
     *  The channel map update instant has passed.
     */
    PROCEDURE_ABORT_REASON_CHANNEL_MAP_UPDATE_INSTANT_PASSED,
    /** \brief
     *  Unspecified abort reason.
     */
    PROCEDURE_ABORT_REASON_UNSPECIFIED,
    /** \brief
     *  Reserved abort reason.
     */
    PROCEDURE_ABORT_REASON_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ProcedureAbortReason_t;

/** \brief
 *  Reasons for aborting subevents.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum SubeventAbortReason {
    /** \brief
     *  The subevent was not aborted.
     */
    SUBEVENT_ABORT_REASON_NO_ABORT,
    /** \brief
     *  Abort caused by local host or a remote request.
     */
    SUBEVENT_ABORT_REASON_LOCAL_HOST_OR_REMOTE_REQUEST,
    /** \brief
     *  No CS sync was received.
     */
    SUBEVENT_ABORT_REASON_NO_CS_SYNC_RECEIVED,
    /** \brief
     *  Scheduling conflict or limited resources.
     */
    SUBEVENT_ABORT_REASON_SCHEDULING_CONFLICT_OR_LIMITED_RESOURCES,
    /** \brief
     *  Unspecified abort reason.
     */
    SUBEVENT_ABORT_REASON_UNSPECIFIED,
    /** \brief
     *  Reserved abort reason.
     */
    SUBEVENT_ABORT_REASON_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
SubeventAbortReason_t;

/** \brief
 *  Discriminant for [`ModeRoleSpecificInfo`].
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ModeRoleSpecificInfoKind {
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE0_REFLECTOR,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_INITIATOR,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_INITIATOR_PBR_RTT,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_REFLECTOR,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE1_REFLECTOR_PBR_RTT,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE2,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_INITIATOR,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_INITIATOR_PBR_RTT,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_REFLECTOR,
    /** <No documentation available> */
    MODE_ROLE_SPECIFIC_INFO_KIND_MODE3_REFLECTOR_PBR_RTT,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ModeRoleSpecificInfoKind_t;

/** \brief
 *  The phase correction term (PCT), composed of I and Q components.
 */
typedef struct PhaseCorrectionTerm {
    /** \brief
     *  The I component of the PCT.
     */
    float i;

    /** \brief
     *  The Q component of the PCT.
     */
    float q;
} PhaseCorrectionTerm_t;

typedef struct {
    PhaseCorrectionTerm_t idx[5];
} PhaseCorrectionTerm_5_array_t;

/** \brief
 *  An indicator of tone quality
 *
 *  Order of entries is important, as it is used for sorting.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ToneQualityIndicator {
    /** \brief
     *  Reserved tone quality indicator.
     */
    TONE_QUALITY_INDICATOR_RESERVED,
    /** \brief
     *  Tone quality is unavailable.
     */
    TONE_QUALITY_INDICATOR_UNAVAILABLE,
    /** \brief
     *  Tone quality is low.
     */
    TONE_QUALITY_INDICATOR_LOW,
    /** \brief
     *  Tone quality is medium.
     */
    TONE_QUALITY_INDICATOR_MEDIUM,
    /** \brief
     *  Tone quality is high.
     */
    TONE_QUALITY_INDICATOR_HIGH,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ToneQualityIndicator_t;

typedef struct {
    ToneQualityIndicator_t idx[5];
} ToneQualityIndicator_5_array_t;

/** \brief
 *  Possible types of extension slots.
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum ExtensionSlot {
    /** \brief
     *  No extension slot is present.
     */
    EXTENSION_SLOT_NOT_PRESENT,
    /** \brief
     *  An extension slot is present but not expected.
     */
    EXTENSION_SLOT_NOT_EXPECTED_PRESENT,
    /** \brief
     *  An extension slot is present and expected.
     */
    EXTENSION_SLOT_EXPECTED_PRESENT,
    /** \brief
     *  Reserved slot type.
     */
    EXTENSION_SLOT_RESERVED,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
ExtensionSlot_t;

typedef struct {
    ExtensionSlot_t idx[5];
} ExtensionSlot_5_array_t;

/** \brief
 *  Content of a Mode2 that is captured in a step.
 */
typedef struct Mode2 {
    /** \brief
     *  The selected antenna permutation index.
     */
    uint8_t antenna_permutation_index;

    /** \brief
     *  The phase correction terms for the antenna paths.
     */
    PhaseCorrectionTerm_5_array_t phase_correction_terms;

    /** \brief
     *  The quality indicators for the antenna paths.
     */
    ToneQualityIndicator_5_array_t quality_indicators;

    /** \brief
     *  The selected extension slots for the antenna paths.
     */
    ExtensionSlot_5_array_t extension_slots;
} Mode2_t;

/** \brief
 *  Mode- and role-specific information.
 *
 *  The `mode2` field is only valid when `kind` is [`ModeRoleSpecificInfoKind::Mode2`].
 */
typedef struct ModeRoleSpecificInfo {
    /** \brief
     *  The kind of mode- and role-specific information.
     */
    ModeRoleSpecificInfoKind_t kind;

    /** \brief
     *  Mode2 data. Only valid when `kind` is [`ModeRoleSpecificInfoKind::Mode2`].
     */
    Mode2_t mode2;
} ModeRoleSpecificInfo_t;

/** \brief
 *  Data that characterizes a step.
 */
typedef struct Step {
    /** \brief
     *  The type of mode.
     */
    uint8_t mode;

    /** \brief
     *  The selected frequency channel.
     */
    uint8_t channel;

    /** \brief
     *  Information that is specific to the mode and role of a node.
     */
    ModeRoleSpecificInfo_t info;
} Step_t;

typedef struct {
    Step_t idx[160];
} Step_160_array_t;

/** \brief
 *  The relative frequency error compensation.
 */
typedef struct FrequencyCompensation {
    /** \brief
     *  The compensation value in steps of 0.01 ppm.
     */
    uint16_t value;
} FrequencyCompensation_t;

/** \brief
 *  A reference power level in dBm.
 */
typedef struct ReferencePowerLevel {
    /** \brief
     *  The reference power level value in dBm, from -127 to 20.
     */
    int8_t value;
} ReferencePowerLevel_t;

/** \brief
 *  Metadata that is contained only in the initial HCI_LE_CS_Config_Complete subevent.
 */
typedef struct InitialMeta {
    /** \brief
     *  Starting ACL connection event counter for the results reported in the event.
     */
    uint16_t start_acl_conn_event_counter;

    /** \brief
     *  If true, the metadata contains a valid starting ACL connection event counter.
     */
    bool has_start_acl_conn_event_counter;

    /** \brief
     *  CS procedure count since completion of the Channel Sounding Security Start procedure.
     */
    uint16_t procedure_counter;

    /** \brief
     *  Frequency compensation with a resolution of 0.01 ppm.
     */
    FrequencyCompensation_t frequency_compensation;

    /** \brief
     *  The reference power level between -127 and 20 dBm.
     */
    ReferencePowerLevel_t reference_power_level;
} InitialMeta_t;

/** \brief
 *  Data that was collected from a "LE CS Subevent Result event" [7.7.65.44, p. 2446]
 *  or a "LE CS Subevent Result Continue event" [7.7.65.45, p. 2459].
 *
 *  For the latter, the [`SubeventResultEvent::initial_meta`] is `None`.
 */
typedef struct SubeventResultEvent {
    /** \brief
     *  The origin of the data (initiator or reflector).
     */
    Origin_t origin;

    /** \brief
     *  MAC address of the local node.
     */
    uint64_t local_mac;

    /** \brief
     *  MAC address of the peer node.
     */
    uint64_t peer_mac;

    /** \brief
     *  The connection handle between two nodes.
     */
    uint16_t connection_handle;

    /** \brief
     *  CS configuration identifier.
     */
    uint8_t config_id;

    /** \brief
     *  If true, has valid config ID.
     */
    bool has_config_id;

    /** \brief
     *  State of the procedure.
     */
    DoneStatus_t procedure_done_status;

    /** \brief
     *  The procedure abort reason, if any.
     */
    ProcedureAbortReason_t procedure_abort_reason;

    /** \brief
     *  State of the subevent.
     */
    DoneStatus_t subevent_done_status;

    /** \brief
     *  The subevent abort reason, if any.
     */
    SubeventAbortReason_t subevent_abort_reason;

    /** \brief
     *  The number of antenna paths.
     */
    size_t antenna_path_count;

    /** \brief
     *  The number of steps for the subevent.
     */
    size_t step_count;

    /** \brief
     *  The step data.
     */
    Step_160_array_t steps;

    /** \brief
     *  Metadata that only the first subevent (not the "continue" variant) holds.
     */
    InitialMeta_t initial_meta;

    /** \brief
     *  If true, initial metadata is available.
     */
    bool has_initial_meta;
} SubeventResultEvent_t;

/** \brief
 *  Serialize a subevent result event to [`SerializedData`].
 */
SerializedData_t
serialize_subevent_result_event (
    SubeventResultEvent_t const * p_event,
    bool use_cobs);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_BLUETOOTH_HCI__ */
